version: '3.7'

services:

  php:
    build:
      context: .
      args:
        PHP_VERSION:    7
        ALPINE_VERSION: 3.9
        TZ:             "Europe/Berlin"
        INTL:           "de_DE"
        http_proxy:     ${http_proxy}
        https_proxy:    ${https_proxy}
        no_proxy:       ${no_proxy}
        HTTP_PROXY_REQUEST_FULLURI:  ${HTTP_PROXY_REQUEST_FULLURI}
        HTTPS_PROXY_REQUEST_FULLURI: ${HTTPS_PROXY_REQUEST_FULLURI}
    image: zierf/php:7-fpm-alpine
    #ports:
    # - '9000:9000'
    # - '9009:9009'
    #volumes:
    # - ./conf/ssl/certs:/usr/local/share/ca-certificates:ro
    # - ./conf/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
    # - ./conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    # - ./conf/openldap:/etc/openldap:ro
    env_file:
      - .env
    restart: never
