version: '3.5'

services:

  php:
    build:
      context: .
      args:
        TZ:           "Europe/Berlin"
        INTL:         "de_DE"
        #HTTP_PROXY:  "http://proxy.domain.tld:8080"
        #HTTPS_PROXY: "https://proxy.domain.tld:4443"
        #FTP_PROXY:   "ftp://proxy.domain.tld:2121"
        #NO_PROXY:    "localhost,127.0.0.1,.domain.local"
        #HTTP_PROXY_REQUEST_FULLURI:  "false"
        #HTTPS_PROXY_REQUEST_FULLURI: "false"
    image: zierf/php:7-fpm-alpine
    restart: never
    #ports:
    #  - '9000:9000'
    #  - '9004:9004'
